### ISSUE TITLE
Project details

### ISSUE THREAD

**Issue by antisvin** [4ms/mp1-brainboard-demo#1]
So this is the platform for upcoming 4MS looping delay & sampler modules and likely more will follow later. AFAICT, the digital board has:

- STM32MP153 CPU (btw, makefile sets `-DSTM32MP157Cxx` variable here, might be a mistake - https://github.com/4ms/mp1-brainboard-demo/blob/makefile/Makefile#L84)
- 512 MB DDR
- PCM3060 codec (like Daisy Patch SM!)
- flashable via DFU

There's also a version for F7 which might be for an earlier prototype or some alternative board (but then I'd expect H7 to be used).

It would be interesting to hear any other details or plans for this hardware.

**Comment by danngreen** [comment]
So, we actually have several brain-boards that can be used with the new line of modules and kits. The DSP code for each model is platform-agnostic. Some future models might require a certain brain board (i.e. a huge reverb model might require an MP1 brain-board), but the Sampler and Looping Delay work on any brain-board.

This repo just demonstrates the MP153 brain-board. I'm still undecided how to structure all the projects into repositories: there are multiple module cores (sampler, looping delay, more to come) times multiple brain-boards (F723, MP153 so far, and MP131 is in progress). Plus there are bootloaders for each platform and the MP1 series require an SSBL for USB-DFU loading. I'm
considering one mono-repo with all projects in it, or else making a repo for all brain boards and their bootloaders, plus one repo for each module. In the latter case, we would include the brain board repo as a submodule into each module repo.

**Comment by antisvin** [comment]
Is it correct that the Looping delay & Sampler modules/kits will always be shipped with MP153 brain-board version? Asking this to understand if they can be considered a sort of eurorack dev kit for this CPU.

If it matters, my preference would be to have a single repo with core code and build scripts. The hardware specific projects could be either in the same repo  or in separate repos (specified by local path when building). I'm not a big fan of using core repo as a submodule as it requires extra maintenance for syncing everything on every change, but I guess it may be useful in certain cases (like wishing to freeze firmware state when it's ready to be shipped).

**Comment by danngreen** [comment]
The first batch of Sampler and LD kits will ship with the F723 brain board. Future batches might ship with MP1x or some other chip. Some future models of kits will ship with an MP1x board.

My end goal is to have an MP131 brain board with 512MB RAM, since that's the best chip suited for simple audio devices (single core A7). I'm considering selling an MP153 version of the brain board right away as an "upgrade" for hobbyists or those wishing to develop on this platform, since I already have that prototyped. But we might do an MP135 board instead since those are available and are pin-compatible with the MP131.

As far as the repo organization, a build flag for the local path to the shared code is not bad, though during development having the module code and shared code in sync is critical. But it might be a way to go once the brain boards are stable.
Have you used git subtrees in a real-world situation? I haven't, but it sounds like it's worth trying. My understanding is that pulling in an update to the shared code makes it appear as a normal git commit (no separate submodule git status). This solves the sync issue because no developer could have it the core code out of sync by forgetting to run some git command (as is the case with git submodules). Pushing changes to the shared code from within a module-specific project takes more effort, but it's still possible.

**Comment by antisvin** [comment]
Ok, thanks for the clarifications, I think my curiosity is finally satisfied. The reason why I thought that it would be shipped with MP1 board is that it was on photos for kit pages of these modules, this was a bit confusing. But that's ok, I can wait for hardware availability.

I definitely agree that MP13x would be the most reasonable choice for audio. Still, there are cases where code can be relatively easy parallelized to utilize multiple cores (multichannel audio, polyphony). Another example where the second core would be quite helpful is for rendering graphics on a large display - with no DMA2D and GPU being useless without OS, this would have to be done with CPU only.

I have not used git subtrees unfortunately. This article was a very nice explanation of typical usage patterns - https://medium.com/@porteneuve/mastering-git-subtrees-943d29a798ec . Looks like subtree implementation is somewhat a leaky abstraction (pollutes history with subrepo commit history even with squashing, adds extra branches). But it solves the most common user errors that submodules are prone to.
